---

- name: Install marathon
  apt: name=marathon state=present

# Create marathon configuration directory
- name: Create Marathon configuration directory
  file: path=/etc/marathon/conf state=directory

# Set the hostnames for each server's marathon instance
- name: Set marathon hostnames
  copy: content={{marathon_ip}} dest=/etc/marathon/conf/hostname
  notify: Restart marathon

# Define zookeeper masters for marathon
- name: Define zookeeper masters for marathon
  copy: content={{marathon_zk}} dest=/etc/marathon/conf/zk
# Define the zookeeper masters
